// Generated by tools/generate_rust_bindings.py; do not edit.
#![allow(non_camel_case_types, non_upper_case_globals)]
use std::ffi::{c_char,c_void,c_int,c_uint,c_float,c_double,c_uchar};
// cui.h
#[repr(C)] pub struct cui_app { _private: [u8;0] }
#[repr(C)] pub struct cui_window { _private: [u8;0] }
#[repr(C)] pub struct cui_widget { _private: [u8;0] }
#[repr(C)] pub struct cui_timer { _private: [u8;0] }
#[repr(C)] pub struct cui_icon_asset { _private: [u8;0] }
pub type cui_key = c_int;
pub const CUI_KEY_BACKSPACE: cui_key = 8;
pub const CUI_KEY_TAB: cui_key = 9;
pub const CUI_KEY_ENTER: cui_key = 13;
pub const CUI_KEY_ESCAPE: cui_key = 27;
pub const CUI_KEY_UP: cui_key = 256;
pub const CUI_KEY_DOWN: cui_key = 257;
pub const CUI_KEY_HOME: cui_key = 258;
pub const CUI_KEY_END: cui_key = 259;
pub type cui_axis = c_int;
pub const CUI_HORIZONTAL: cui_axis = 0;
pub const CUI_VERTICAL: cui_axis = 1;
pub type cui_theme = c_int;
pub const CUI_THEME_SYSTEM: cui_theme = 0;
pub const CUI_THEME_LIGHT: cui_theme = 1;
pub const CUI_THEME_DARK: cui_theme = 2;
pub type cui_role = c_int;
pub const CUI_ROLE_BODY: cui_role = 0;
pub const CUI_ROLE_TITLE: cui_role = 1;
pub const CUI_ROLE_HEADING: cui_role = 2;
pub const CUI_ROLE_CAPTION: cui_role = 3;
pub const CUI_ROLE_PRIMARY: cui_role = 4;
pub const CUI_ROLE_CARD: cui_role = 5;
pub const CUI_ROLE_SUCCESS: cui_role = 6;
pub const CUI_ROLE_WARNING: cui_role = 7;
pub const CUI_ROLE_DANGER: cui_role = 8;
pub const CUI_ROLE_SUBTLE: cui_role = 9;
pub const CUI_ROLE_PANEL: cui_role = 10;
pub const CUI_ROLE_CHAT_BACKGROUND: cui_role = 11;
pub const CUI_ROLE_MESSAGE: cui_role = 12;
pub const CUI_ROLE_OUTGOING: cui_role = 13;
pub const CUI_ROLE_FLAT: cui_role = 14;
pub const CUI_ROLE_AMBIENT: cui_role = 15;
pub type cui_symbol = c_int;
pub const CUI_SYMBOL_NONE: cui_symbol = 0;
pub const CUI_SYMBOL_PLAY: cui_symbol = 1;
pub const CUI_SYMBOL_PAUSE: cui_symbol = 2;
pub const CUI_SYMBOL_PREVIOUS: cui_symbol = 3;
pub const CUI_SYMBOL_NEXT: cui_symbol = 4;
pub const CUI_SYMBOL_VOLUME: cui_symbol = 5;
pub const CUI_SYMBOL_MUTED: cui_symbol = 6;
pub const CUI_SYMBOL_SHUFFLE: cui_symbol = 7;
pub const CUI_SYMBOL_REPEAT: cui_symbol = 8;
pub const CUI_SYMBOL_SEARCH: cui_symbol = 9;
pub const CUI_SYMBOL_MENU: cui_symbol = 10;
pub const CUI_SYMBOL_MORE: cui_symbol = 11;
pub const CUI_SYMBOL_ATTACH: cui_symbol = 12;
pub const CUI_SYMBOL_SEND: cui_symbol = 13;
pub const CUI_SYMBOL_HEART: cui_symbol = 14;
pub const CUI_SYMBOL_HEART_FILLED: cui_symbol = 15;
pub const CUI_SYMBOL_REPLY: cui_symbol = 16;
pub const CUI_SYMBOL_INFO: cui_symbol = 17;
pub const CUI_SYMBOL_CLOSE: cui_symbol = 18;
pub const CUI_SYMBOL_PLUS: cui_symbol = 19;
pub const CUI_SYMBOL_CHECK: cui_symbol = 20;
pub const CUI_SYMBOL_UP: cui_symbol = 21;
pub const CUI_SYMBOL_DOWN: cui_symbol = 22;
pub const CUI_SYMBOL_PIN: cui_symbol = 23;
pub const CUI_SYMBOL_ARCHIVE: cui_symbol = 24;
pub const CUI_SYMBOL_MAIL: cui_symbol = 25;
pub const CUI_SYMBOL_EDIT: cui_symbol = 26;
pub const CUI_SYMBOL_COUNT: cui_symbol = 27;
pub type cui_icon_op = c_int;
pub const CUI_ICON_MOVE: cui_icon_op = 0;
pub const CUI_ICON_LINE: cui_icon_op = 1;
pub const CUI_ICON_CUBIC: cui_icon_op = 2;
pub const CUI_ICON_CLOSE: cui_icon_op = 3;
pub const CUI_ICON_FILL: cui_icon_op = 4;
pub const CUI_ICON_STROKE: cui_icon_op = 5;
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_icon_command {pub op: cui_icon_op,pub values: [c_float; 6],pub rgba: c_uint,pub current_color: c_int,}
impl Default for cui_icon_command { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_desktop.h
#[repr(C)] pub struct cui_dialog { _private: [u8;0] }
#[repr(C)] pub struct cui_command { _private: [u8;0] }
#[repr(C)] pub struct cui_menu { _private: [u8;0] }
pub type cui_dialog_kind = c_int;
pub const CUI_DIALOG_OPEN: cui_dialog_kind = 0;
pub const CUI_DIALOG_SAVE: cui_dialog_kind = 1;
pub const CUI_DIALOG_FOLDER: cui_dialog_kind = 2;
pub const CUI_DIALOG_ALERT: cui_dialog_kind = 3;
pub const CUI_DIALOG_COLOR: cui_dialog_kind = 4;
pub const CUI_DIALOG_FONT: cui_dialog_kind = 5;
pub type cui_dialog_result = c_int;
pub const CUI_DIALOG_CANCELLED: cui_dialog_result = 0;
pub const CUI_DIALOG_ACCEPTED: cui_dialog_result = 1;
pub const CUI_DIALOG_FAILED: cui_dialog_result = 2;
pub type cui_modifiers = c_int;
pub const CUI_MOD_SHIFT: cui_modifiers = 1;
pub const CUI_MOD_ALT: cui_modifiers = 2;
pub const CUI_MOD_CONTROL: cui_modifiers = 4;
pub const CUI_MOD_PRIMARY: cui_modifiers = 8;
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_file_filter {pub name: *const c_char,pub extensions: *const *const c_char,pub extension_count: usize,}
impl Default for cui_file_filter { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_file_options {pub initial_path: *const c_char,pub filters: *const cui_file_filter,pub filter_count: usize,pub initial_filter: usize,pub multiple: c_int,}
impl Default for cui_file_options { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_font_value {pub family: [c_char; 129],pub points: c_double,pub weight: c_int,pub italic: c_int,}
impl Default for cui_font_value { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_draw.h
#[repr(C)] pub struct cui_surface { _private: [u8;0] }
pub type cui_draw_op = c_int;
pub const CUI_DRAW_CLEAR: cui_draw_op = 0;
pub const CUI_DRAW_SAVE: cui_draw_op = 1;
pub const CUI_DRAW_RESTORE: cui_draw_op = 2;
pub const CUI_DRAW_TRANSLATE: cui_draw_op = 3;
pub const CUI_DRAW_SCALE: cui_draw_op = 4;
pub const CUI_DRAW_CLIP: cui_draw_op = 5;
pub const CUI_DRAW_LAYER: cui_draw_op = 6;
pub const CUI_DRAW_END_LAYER: cui_draw_op = 7;
pub const CUI_DRAW_RECT: cui_draw_op = 8;
pub const CUI_DRAW_ELLIPSE: cui_draw_op = 9;
pub const CUI_DRAW_LINE: cui_draw_op = 10;
pub const CUI_DRAW_ICON: cui_draw_op = 11;
pub const CUI_DRAW_TEXT: cui_draw_op = 12;
pub const CUI_DRAW_GRADIENT: cui_draw_op = 13;
pub const CUI_DRAW_SHADOW: cui_draw_op = 14;
pub const CUI_DRAW_MATERIAL: cui_draw_op = 15;
pub type cui_draw_align = c_int;
pub const CUI_DRAW_ALIGN_LEFT: cui_draw_align = 0;
pub const CUI_DRAW_ALIGN_CENTER: cui_draw_align = 1;
pub const CUI_DRAW_ALIGN_RIGHT: cui_draw_align = 2;
pub type cui_canvas_event_kind = c_int;
pub const CUI_CANVAS_PRESS: cui_canvas_event_kind = 0;
pub const CUI_CANVAS_RELEASE: cui_canvas_event_kind = 1;
pub const CUI_CANVAS_MOVE: cui_canvas_event_kind = 2;
pub const CUI_CANVAS_SCROLL: cui_canvas_event_kind = 3;
pub const CUI_CANVAS_ACTIVATE: cui_canvas_event_kind = 4;
pub const CUI_CANVAS_FOCUS: cui_canvas_event_kind = 5;
pub type cui_draw_capability = c_int;
pub const CUI_DRAW_ALPHA: cui_draw_capability = 1;
pub const CUI_DRAW_GROUPS: cui_draw_capability = 2;
pub const CUI_DRAW_BLUR: cui_draw_capability = 4;
pub const CUI_DRAW_TEXT_SHAPING: cui_draw_capability = 8;
pub const CUI_DRAW_REGIONS: cui_draw_capability = 16;
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_draw_command {pub op: cui_draw_op,pub p: [c_float; 8],pub color: c_uint,pub color2: c_uint,pub text: *const c_char,pub font: *const c_char,pub icon: *const cui_icon_asset,}
impl Default for cui_draw_command { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_canvas_event {pub kind: cui_canvas_event_kind,pub id: c_uint,pub x: c_double,pub y: c_double,pub dx: c_double,pub dy: c_double,pub modifiers: c_uint,}
impl Default for cui_canvas_event { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_canvas_region {pub id: c_uint,pub x: c_float,pub y: c_float,pub width: c_float,pub height: c_float,pub label: *const c_char,pub enabled: c_int,}
impl Default for cui_canvas_region { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_feedback.h
pub type cui_feedback_kind = c_int;
pub const CUI_BANNER: cui_feedback_kind = 0;
pub const CUI_TOAST: cui_feedback_kind = 1;
pub const CUI_EMPTY_STATE: cui_feedback_kind = 2;
pub const CUI_ERROR_STATE: cui_feedback_kind = 3;
pub type cui_feedback_event = c_int;
pub const CUI_FEEDBACK_NONE: cui_feedback_event = 0;
pub const CUI_FEEDBACK_ACTION: cui_feedback_event = 1;
pub const CUI_FEEDBACK_DISMISS: cui_feedback_event = 2;
pub const CUI_FEEDBACK_TIMEOUT: cui_feedback_event = 3;
pub type cui_feedback_part = c_int;
pub const CUI_FEEDBACK_TITLE: cui_feedback_part = 0;
pub const CUI_FEEDBACK_MESSAGE: cui_feedback_part = 1;
pub const CUI_FEEDBACK_ACTION_BUTTON: cui_feedback_part = 2;
pub const CUI_FEEDBACK_DISMISS_BUTTON: cui_feedback_part = 3;
// cui_inputs.h
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_date_value {pub year: c_int,pub month: c_int,pub day: c_int,}
impl Default for cui_date_value { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_time_value {pub hour: c_int,pub minute: c_int,pub second: c_int,}
impl Default for cui_time_value { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_layouts.h
// cui_navigation.h
pub type cui_tree_event = c_int;
pub const CUI_TREE_NONE: cui_tree_event = 0;
pub const CUI_TREE_SELECTION: cui_tree_event = 1;
pub const CUI_TREE_EXPAND: cui_tree_event = 2;
pub const CUI_TREE_COLLAPSE: cui_tree_event = 3;
pub const CUI_TREE_ACTIVATE: cui_tree_event = 4;
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_tree_item {pub id: cui_item_id,pub parent: cui_item_id,pub text: *const c_char,pub expanded: c_int,}
impl Default for cui_tree_item { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_breadcrumb_item {pub id: cui_item_id,pub text: *const c_char,}
impl Default for cui_breadcrumb_item { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_patterns.h
pub type cui_pattern = c_int;
pub const CUI_LOADING: cui_pattern = 0;
pub const CUI_THINKING: cui_pattern = 1;
pub const CUI_STREAMING: cui_pattern = 2;
pub const CUI_APPROVAL: cui_pattern = 3;
pub const CUI_TOOL_CHIPS: cui_pattern = 4;
pub const CUI_TASK_ROWS: cui_pattern = 5;
pub const CUI_CHAT: cui_pattern = 6;
pub const CUI_PROMPT_BAR: cui_pattern = 7;
pub const CUI_RECOMMENDATION: cui_pattern = 8;
pub const CUI_CONTEXT: cui_pattern = 9;
pub const CUI_DIFF_TABLE: cui_pattern = 10;
pub const CUI_RECORDS_TABLE: cui_pattern = 11;
pub const CUI_FILTER_TABLE: cui_pattern = 12;
pub const CUI_SIDEBAR: cui_pattern = 13;
pub const CUI_SEARCH_PANEL: cui_pattern = 14;
pub const CUI_FLOWCHART: cui_pattern = 15;
pub const CUI_INSIGHTS: cui_pattern = 16;
pub const CUI_CODE_BLOCK: cui_pattern = 17;
pub const CUI_FINE_TUNE: cui_pattern = 18;
pub const CUI_SELECTION_ACTIONS: cui_pattern = 19;
pub const CUI_AGENT_SCREEN: cui_pattern = 20;
pub const CUI_PATTERN_COUNT: cui_pattern = 21;
pub type cui_part = c_int;
pub const CUI_PART_TITLE: cui_part = 0;
pub const CUI_PART_BODY: cui_part = 1;
pub const CUI_PART_INPUT: cui_part = 2;
pub const CUI_PART_PRIMARY: cui_part = 3;
pub const CUI_PART_SECONDARY: cui_part = 4;
pub const CUI_PART_CHOICE: cui_part = 5;
pub const CUI_PART_STATUS: cui_part = 6;
pub const CUI_PART_PROGRESS: cui_part = 7;
pub const CUI_PART_DETAILS: cui_part = 8;
pub const CUI_PART_CHART: cui_part = 9;
pub const CUI_PART_PREVIEW: cui_part = 10;
pub const CUI_PART_AUXILIARY: cui_part = 11;
pub const CUI_PART_COUNT: cui_part = 12;
pub type cui_event = c_int;
pub const CUI_EVENT_NONE: cui_event = 0;
pub const CUI_EVENT_SUBMIT: cui_event = 1;
pub const CUI_EVENT_CANCEL: cui_event = 2;
pub const CUI_EVENT_SELECT: cui_event = 3;
pub const CUI_EVENT_CHANGE: cui_event = 4;
pub const CUI_EVENT_OPEN: cui_event = 5;
pub const CUI_EVENT_DICTATE: cui_event = 6;
pub const CUI_EVENT_TRANSFORM: cui_event = 7;
pub type cui_filter_op = c_int;
pub const CUI_FILTER_CONTAINS: cui_filter_op = 0;
pub const CUI_FILTER_EQUALS: cui_filter_op = 1;
pub const CUI_FILTER_NOT_EQUALS: cui_filter_op = 2;
pub const CUI_FILTER_STARTS_WITH: cui_filter_op = 3;
pub const CUI_FILTER_ENDS_WITH: cui_filter_op = 4;
pub const CUI_FILTER_LESS: cui_filter_op = 5;
pub const CUI_FILTER_LESS_EQUAL: cui_filter_op = 6;
pub const CUI_FILTER_GREATER: cui_filter_op = 7;
pub const CUI_FILTER_GREATER_EQUAL: cui_filter_op = 8;
pub const CUI_FILTER_EMPTY: cui_filter_op = 9;
pub const CUI_FILTER_NOT_EMPTY: cui_filter_op = 10;
pub type cui_pattern_item_flags = c_int;
pub const CUI_ITEM_EXPANDED: cui_pattern_item_flags = 1;
pub const CUI_ITEM_DISABLED: cui_pattern_item_flags = 2;
pub const CUI_ITEM_COMPLETE: cui_pattern_item_flags = 4;
pub const CUI_ITEM_SELECTED: cui_pattern_item_flags = 8;
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_record_filter {pub column: usize,pub operation: cui_filter_op,pub value: *const c_char,}
impl Default for cui_record_filter { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_insight_series {pub id: cui_item_id,pub title: *const c_char,pub detail: *const c_char,pub values: *const c_double,pub labels: *const *const c_char,pub count: usize,}
impl Default for cui_insight_series { fn default()->Self { unsafe { std::mem::zeroed() } } }
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_pattern_item {pub id: cui_item_id,pub title: *const c_char,pub body: *const c_char,pub detail: *const c_char,pub badge: *const c_char,pub progress: c_double,pub tone: cui_role,pub flags: c_uint,}
impl Default for cui_pattern_item { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_search.h
pub type cui_picker_kind = c_int;
pub const CUI_AUTOCOMPLETE: cui_picker_kind = 0;
pub const CUI_COMMAND_PALETTE: cui_picker_kind = 1;
pub type cui_picker_event = c_int;
pub const CUI_PICKER_NONE: cui_picker_event = 0;
pub const CUI_PICKER_QUERY: cui_picker_event = 1;
pub const CUI_PICKER_SELECT: cui_picker_event = 2;
pub const CUI_PICKER_SUBMIT: cui_picker_event = 3;
pub const CUI_PICKER_CANCEL: cui_picker_event = 4;
pub type cui_picker_part = c_int;
pub const CUI_PICKER_INPUT: cui_picker_part = 0;
pub const CUI_PICKER_RESULTS: cui_picker_part = 1;
pub const CUI_PICKER_STATUS: cui_picker_part = 2;
pub const CUI_PICKER_ACCEPT: cui_picker_part = 3;
pub const CUI_PICKER_CLOSE: cui_picker_part = 4;
#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct cui_choice {pub id: cui_item_id,pub label: *const c_char,pub detail: *const c_char,pub keywords: *const c_char,pub disabled: c_int,}
impl Default for cui_choice { fn default()->Self { unsafe { std::mem::zeroed() } } }
// cui_tables.h
pub type cui_table_event = c_int;
pub const CUI_TABLE_NONE: cui_table_event = 0;
pub const CUI_TABLE_SELECTION: cui_table_event = 1;
pub const CUI_TABLE_EDIT: cui_table_event = 2;
pub const CUI_TABLE_SORT: cui_table_event = 3;
// cui_tokens.h
pub type cui_tokens_event = c_int;
pub const CUI_TOKENS_NONE: cui_tokens_event = 0;
pub const CUI_TOKENS_ADD: cui_tokens_event = 1;
pub const CUI_TOKENS_REMOVE: cui_tokens_event = 2;
pub const CUI_TOKENS_CLEAR: cui_tokens_event = 3;
pub const CUI_TOKENS_QUERY: cui_tokens_event = 4;
pub const CUI_TOKENS_SUBMIT: cui_tokens_event = 5;
pub type cui_tokens_part = c_int;
pub const CUI_TOKENS_INPUT: cui_tokens_part = 0;
pub const CUI_TOKENS_PICKER: cui_tokens_part = 1;
pub const CUI_TOKENS_CHIPS: cui_tokens_part = 2;
pub const CUI_TOKENS_STATUS: cui_tokens_part = 3;
pub const CUI_TOKENS_CLEAR_BUTTON: cui_tokens_part = 4;
pub type cui_canvas_callback = Option<unsafe extern "C" fn(*mut cui_widget,*const cui_canvas_event,*mut c_void)>;
pub type cui_item_id = u64;
pub type cui_callback = Option<unsafe extern "C" fn(*mut cui_widget,*mut c_void)>;
pub type cui_task = Option<unsafe extern "C" fn(*mut c_void)>;
pub type cui_key_callback = Option<unsafe extern "C" fn(*mut cui_widget,cui_key,c_uint,*mut c_void)->c_int>;
pub type cui_dialog_callback = Option<unsafe extern "C" fn(*mut cui_dialog,cui_dialog_result,*const c_char,*mut c_void)>;
unsafe extern "C" {
    pub fn cui_on_key(entry: *mut cui_widget, callback: cui_key_callback, userdata: *mut c_void) -> c_int;
    pub fn cui_icon_vector(width: c_float, height: c_float, commands: *const cui_icon_command, count: usize) -> *mut cui_icon_asset;
    pub fn cui_icon_rgba(pixels: *const c_uchar, width: c_int, height: c_int) -> *mut cui_icon_asset;
    pub fn cui_icon_symbol(symbol: cui_symbol) -> *mut cui_icon_asset;
    pub fn cui_icon_load(path: *const c_char) -> *mut cui_icon_asset;
    pub fn cui_icon_load_image(path: *const c_char) -> *mut cui_icon_asset;
    pub fn cui_icon_decode(bytes: *const c_void, length: usize) -> *mut cui_icon_asset;
    pub fn cui_icon_retain(asset: *mut cui_icon_asset) -> *mut cui_icon_asset;
    pub fn cui_icon_release(asset: *mut cui_icon_asset);
    pub fn cui_icon(parent: *mut cui_widget, asset: *mut cui_icon_asset) -> *mut cui_widget;
    pub fn cui_icon_button(parent: *mut cui_widget, asset: *mut cui_icon_asset, accessible_label: *const c_char) -> *mut cui_widget;
    pub fn cui_set_icon(widget: *mut cui_widget, asset: *mut cui_icon_asset) -> c_int;
    pub fn cui_get_icon(widget: *const cui_widget) -> *mut cui_icon_asset;
    pub fn cui_set_icon_size(widget: *mut cui_widget, logical_size: c_int) -> c_int;
    pub fn cui_set_icon_only(widget: *mut cui_widget, icon_only: c_int) -> c_int;
    pub fn cui_app_create() -> *mut cui_app;
    pub fn cui_app_run(app: *mut cui_app);
    pub fn cui_app_quit(app: *mut cui_app);
    pub fn cui_app_destroy(app: *mut cui_app);
    pub fn cui_app_error(app: *const cui_app) -> *const c_char;
    pub fn cui_app_set_theme(app: *mut cui_app, theme: cui_theme);
    pub fn cui_app_set_text_scale(app: *mut cui_app, scale: c_double) -> c_int;
    pub fn cui_set_font(widget: *mut cui_widget, family: *const c_char, points: c_double, weight: c_int) -> c_int;
    pub fn cui_window_scale(window: *const cui_window) -> c_double;
    pub fn cui_every(app: *mut cui_app, milliseconds: c_uint, task: cui_task, userdata: *mut c_void) -> *mut cui_timer;
    pub fn cui_timer_stop(timer: *mut cui_timer);
    pub fn cui_timer_start(timer: *mut cui_timer) -> c_int;
    pub fn cui_time() -> c_double;
    pub fn cui_window_create(app: *mut cui_app, title: *const c_char, width: c_int, height: c_int) -> *mut cui_window;
    pub fn cui_window_root(window: *mut cui_window) -> *mut cui_widget;
    pub fn cui_window_show(window: *mut cui_window);
    pub fn cui_window_close(window: *mut cui_window);
    pub fn cui_window_set_frame(window: *mut cui_window, decorated: c_int, resizable: c_int, corner_radius: c_double) -> c_int;
    pub fn cui_window_set_size(window: *mut cui_window, width: c_int, height: c_int) -> c_int;
    pub fn cui_window_set_position(window: *mut cui_window, x: c_int, y: c_int) -> c_int;
    pub fn cui_window_begin_move(window: *mut cui_window) -> c_int;
    pub fn cui_window_get_size(window: *mut cui_window, width: *mut c_int, height: *mut c_int) -> c_int;
    pub fn cui_window_begin_resize(window: *mut cui_window, corner: c_int) -> c_int;
    pub fn cui_window_set_anchor(panel: *mut cui_window, parent: *mut cui_window, x: c_int, y: c_int, width: c_int, height: c_int) -> c_int;
    pub fn cui_window_is_visible(window: *const cui_window) -> c_int;
    pub fn cui_window_set_scrollable(window: *mut cui_window, scrollable: c_int);
    pub fn cui_box(parent: *mut cui_widget, axis: cui_axis, gap: c_int) -> *mut cui_widget;
    pub fn cui_box_set_padding(box_: *mut cui_widget, padding: c_int);
    pub fn cui_label(parent: *mut cui_widget, text: *const c_char) -> *mut cui_widget;
    pub fn cui_button(parent: *mut cui_widget, text: *const c_char) -> *mut cui_widget;
    pub fn cui_entry(parent: *mut cui_widget, text: *const c_char) -> *mut cui_widget;
    pub fn cui_checkbox(parent: *mut cui_widget, text: *const c_char, checked: c_int) -> *mut cui_widget;
    pub fn cui_toggle(parent: *mut cui_widget, text: *const c_char, checked: c_int) -> *mut cui_widget;
    pub fn cui_switch(parent: *mut cui_widget, text: *const c_char, checked: c_int) -> *mut cui_widget;
    pub fn cui_radio(parent: *mut cui_widget, text: *const c_char, checked: c_int) -> *mut cui_widget;
    pub fn cui_password(parent: *mut cui_widget, text: *const c_char) -> *mut cui_widget;
    pub fn cui_search(parent: *mut cui_widget, placeholder: *const c_char) -> *mut cui_widget;
    pub fn cui_textarea(parent: *mut cui_widget, text: *const c_char) -> *mut cui_widget;
    pub fn cui_code(parent: *mut cui_widget, text: *const c_char) -> *mut cui_widget;
    pub fn cui_select(parent: *mut cui_widget, items: *const *const c_char, count: usize) -> *mut cui_widget;
    pub fn cui_list(parent: *mut cui_widget, items: *const *const c_char, count: usize) -> *mut cui_widget;
    pub fn cui_table(parent: *mut cui_widget, headers: *const *const c_char, columns: usize) -> *mut cui_widget;
    pub fn cui_table_set_rows(table: *mut cui_widget, cells: *const *const c_char, rows: usize) -> c_int;
    pub fn cui_set_items(widget: *mut cui_widget, items: *const *const c_char, count: usize) -> c_int;
    pub fn cui_set_selected(widget: *mut cui_widget, index: c_int);
    pub fn cui_get_selected(widget: *const cui_widget) -> c_int;
    pub fn cui_slider(parent: *mut cui_widget, value: c_double) -> *mut cui_widget;
    pub fn cui_progress(parent: *mut cui_widget, value: c_double) -> *mut cui_widget;
    pub fn cui_set_value(widget: *mut cui_widget, value: c_double);
    pub fn cui_get_value(widget: *const cui_widget) -> c_double;
    pub fn cui_spinner(parent: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_separator(parent: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_badge(parent: *mut cui_widget, text: *const c_char, tone: cui_role) -> *mut cui_widget;
    pub fn cui_chart(parent: *mut cui_widget, values: *const c_double, count: usize) -> *mut cui_widget;
    pub fn cui_chart_set_values(chart: *mut cui_widget, values: *const c_double, count: usize) -> c_int;
    pub fn cui_image(parent: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_image_set_rgba(image: *mut cui_widget, pixels: *const c_uchar, width: c_int, height: c_int) -> c_int;
    pub fn cui_clipboard_set_text(window: *mut cui_window, text: *const c_char);
    pub fn cui_set_placeholder(entry: *mut cui_widget, text: *const c_char);
    pub fn cui_set_tooltip(widget: *mut cui_widget, text: *const c_char);
    pub fn cui_set_min_size(widget: *mut cui_widget, width: c_int, height: c_int);
    pub fn cui_set_visible(widget: *mut cui_widget, visible: c_int);
    pub fn cui_tabs(parent: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_tab_add(tabs: *mut cui_widget, title: *const c_char) -> *mut cui_widget;
    pub fn cui_disclosure(parent: *mut cui_widget, title: *const c_char, expanded: c_int) -> *mut cui_widget;
    pub fn cui_disclosure_content(disclosure: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_set_expanded(disclosure: *mut cui_widget, expanded: c_int);
    pub fn cui_get_expanded(disclosure: *const cui_widget) -> c_int;
    pub fn cui_expand(widget: *mut cui_widget, expand: c_int);
    pub fn cui_set_role(widget: *mut cui_widget, role: cui_role);
    pub fn cui_on_action(widget: *mut cui_widget, callback: cui_callback, userdata: *mut c_void);
    pub fn cui_activate(widget: *mut cui_widget) -> c_int;
    pub fn cui_set_text(widget: *mut cui_widget, text: *const c_char);
    pub fn cui_get_text(widget: *const cui_widget, buffer: *mut c_char, capacity: usize) -> usize;
    pub fn cui_get_selected_text(widget: *const cui_widget, buffer: *mut c_char, capacity: usize) -> usize;
    pub fn cui_set_checked(checkbox: *mut cui_widget, checked: c_int);
    pub fn cui_get_checked(checkbox: *const cui_widget) -> c_int;
    pub fn cui_set_enabled(widget: *mut cui_widget, enabled: c_int);
    pub fn cui_focus(widget: *mut cui_widget) -> c_int;
    pub fn cui_has_focus(widget: *const cui_widget) -> c_int;
    pub fn cui_accessibility(widget: *mut cui_widget, label: *const c_char, description: *const c_char);
    pub fn cui_set_read_only(widget: *mut cui_widget, read_only: c_int);
    pub fn cui_undo(widget: *mut cui_widget);
    pub fn cui_redo(widget: *mut cui_widget);
    pub fn cui_file_dialog(parent: *mut cui_window, kind: cui_dialog_kind, title: *const c_char, initial_path: *const c_char, callback: cui_dialog_callback, userdata: *mut c_void) -> *mut cui_dialog;
    pub fn cui_file_dialog_ex(parent: *mut cui_window, kind: cui_dialog_kind, title: *const c_char, options: *const cui_file_options, callback: cui_dialog_callback, userdata: *mut c_void) -> *mut cui_dialog;
    pub fn cui_dialog_path_count(dialog: *const cui_dialog) -> usize;
    pub fn cui_dialog_path(dialog: *const cui_dialog, index: usize) -> *const c_char;
    pub fn cui_dialog_filter(dialog: *const cui_dialog, index: *mut usize) -> c_int;
    pub fn cui_alert(parent: *mut cui_window, title: *const c_char, message: *const c_char, accept_label: *const c_char, callback: cui_dialog_callback, userdata: *mut c_void) -> *mut cui_dialog;
    pub fn cui_dialog_cancel(dialog: *mut cui_dialog);
    pub fn cui_color_dialog(parent: *mut cui_window, title: *const c_char, rgb: c_uint, callback: cui_dialog_callback, userdata: *mut c_void) -> *mut cui_dialog;
    pub fn cui_font_dialog(parent: *mut cui_window, title: *const c_char, font: *const cui_font_value, callback: cui_dialog_callback, userdata: *mut c_void) -> *mut cui_dialog;
    pub fn cui_dialog_color(dialog: *const cui_dialog, rgb: *mut c_uint) -> c_int;
    pub fn cui_dialog_font(dialog: *const cui_dialog, font: *mut cui_font_value) -> c_int;
    pub fn cui_font_apply(widget: *mut cui_widget, font: *const cui_font_value) -> c_int;
    pub fn cui_command_create(app: *mut cui_app, label: *const c_char, key: c_uint, modifiers: c_uint, action: cui_task, userdata: *mut c_void) -> *mut cui_command;
    pub fn cui_command_set_enabled(command: *mut cui_command, enabled: c_int);
    pub fn cui_command_set_checked(command: *mut cui_command, checked: c_int);
    pub fn cui_command_invoke(command: *mut cui_command) -> c_int;
    pub fn cui_menu_create(app: *mut cui_app) -> *mut cui_menu;
    pub fn cui_menu_add(menu: *mut cui_menu, command: *mut cui_command) -> c_int;
    pub fn cui_menu_add_submenu(menu: *mut cui_menu, label: *const c_char, submenu: *mut cui_menu) -> c_int;
    pub fn cui_menu_add_separator(menu: *mut cui_menu) -> c_int;
    pub fn cui_window_set_menu(window: *mut cui_window, menu: *mut cui_menu);
    pub fn cui_menu_popup(menu: *mut cui_menu, anchor: *mut cui_widget);
    pub fn cui_toolbar(parent: *mut cui_widget, commands: *const *mut cui_command, count: usize) -> *mut cui_widget;
    pub fn cui_draw_capabilities() -> c_uint;
    pub fn cui_surface_create(width: c_int, height: c_int, scale: c_double) -> *mut cui_surface;
    pub fn cui_surface_retain(surface: *mut cui_surface) -> *mut cui_surface;
    pub fn cui_surface_release(surface: *mut cui_surface);
    pub fn cui_surface_render(surface: *mut cui_surface, commands: *const cui_draw_command, count: usize) -> c_int;
    pub fn cui_surface_render_region(surface: *mut cui_surface, commands: *const cui_draw_command, count: usize, x: c_double, y: c_double, width: c_double, height: c_double) -> c_int;
    pub fn cui_surface_read(surface: *const cui_surface, rgba: *mut c_uchar, capacity: usize, width: *mut c_int, height: *mut c_int) -> usize;
    pub fn cui_canvas(parent: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_canvas_set_surface(canvas: *mut cui_widget, surface: *mut cui_surface) -> c_int;
    pub fn cui_canvas_set_regions(canvas: *mut cui_widget, regions: *const cui_canvas_region, count: usize) -> c_int;
    pub fn cui_canvas_on_event(canvas: *mut cui_widget, callback: cui_canvas_callback, userdata: *mut c_void);
    pub fn cui_canvas_activate_region(canvas: *mut cui_widget, id: c_uint) -> c_int;
    pub fn cui_canvas_focus_region(canvas: *mut cui_widget, id: c_uint) -> c_int;
    pub fn cui_set_opacity(widget: *mut cui_widget, opacity: c_double) -> c_int;
    pub fn cui_get_opacity(widget: *const cui_widget) -> c_double;
    pub fn cui_feedback(parent: *mut cui_widget, kind: cui_feedback_kind) -> *mut cui_widget;
    pub fn cui_feedback_show(feedback: *mut cui_widget, title: *const c_char, message: *const c_char, tone: cui_role, action: *const c_char, timeout_ms: c_uint) -> c_int;
    pub fn cui_feedback_dismiss(feedback: *mut cui_widget);
    pub fn cui_feedback_pause(feedback: *mut cui_widget, paused: c_int);
    pub fn cui_feedback_is_visible(feedback: *const cui_widget) -> c_int;
    pub fn cui_feedback_last_event(feedback: *const cui_widget) -> cui_feedback_event;
    pub fn cui_feedback_get_part(feedback: *mut cui_widget, part: cui_feedback_part) -> *mut cui_widget;
    pub fn cui_number(parent: *mut cui_widget, value: c_double, minimum: c_double, maximum: c_double, step: c_double, digits: c_uint) -> *mut cui_widget;
    pub fn cui_number_configure(number: *mut cui_widget, minimum: c_double, maximum: c_double, step: c_double, digits: c_uint) -> c_int;
    pub fn cui_number_set(number: *mut cui_widget, value: c_double) -> c_int;
    pub fn cui_number_get(number: *const cui_widget) -> c_double;
    pub fn cui_date(parent: *mut cui_widget, value: cui_date_value) -> *mut cui_widget;
    pub fn cui_date_set(date: *mut cui_widget, value: cui_date_value) -> c_int;
    pub fn cui_date_get(date: *const cui_widget) -> cui_date_value;
    pub fn cui_time_input(parent: *mut cui_widget, value: cui_time_value) -> *mut cui_widget;
    pub fn cui_time_set(time: *mut cui_widget, value: cui_time_value) -> c_int;
    pub fn cui_time_get(time: *const cui_widget) -> cui_time_value;
    pub fn cui_field(parent: *mut cui_widget, label: *const c_char, value: *const c_char, help: *const c_char) -> *mut cui_widget;
    pub fn cui_field_entry(field: *mut cui_widget) -> *mut cui_widget;
    pub fn cui_field_set_error(field: *mut cui_widget, message: *const c_char);
    pub fn cui_field_is_valid(field: *const cui_widget) -> c_int;
    pub fn cui_grid(parent: *mut cui_widget, columns: c_uint, gap: c_int) -> *mut cui_widget;
    pub fn cui_grid_cell(grid: *mut cui_widget, row: c_uint, column: c_uint, row_span: c_uint, column_span: c_uint) -> *mut cui_widget;
    pub fn cui_wrap(parent: *mut cui_widget, gap: c_int) -> *mut cui_widget;
    pub fn cui_split(parent: *mut cui_widget, axis: cui_axis, fraction: c_double) -> *mut cui_widget;
    pub fn cui_split_pane(split: *mut cui_widget, index: c_uint) -> *mut cui_widget;
    pub fn cui_split_set_position(split: *mut cui_widget, fraction: c_double);
    pub fn cui_split_get_position(split: *const cui_widget) -> c_double;
    pub fn cui_tree(parent: *mut cui_widget, items: *const cui_tree_item, count: usize) -> *mut cui_widget;
    pub fn cui_tree_set_items(tree: *mut cui_widget, items: *const cui_tree_item, count: usize) -> c_int;
    pub fn cui_tree_select(tree: *mut cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_tree_selected(tree: *const cui_widget) -> cui_item_id;
    pub fn cui_tree_expand(tree: *mut cui_widget, id: cui_item_id, expanded: c_int) -> c_int;
    pub fn cui_tree_is_expanded(tree: *const cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_tree_last_event(tree: *const cui_widget, id: *mut cui_item_id) -> cui_tree_event;
    pub fn cui_breadcrumbs(parent: *mut cui_widget, items: *const cui_breadcrumb_item, count: usize) -> *mut cui_widget;
    pub fn cui_breadcrumbs_set_items(breadcrumbs: *mut cui_widget, items: *const cui_breadcrumb_item, count: usize) -> c_int;
    pub fn cui_breadcrumbs_current(breadcrumbs: *const cui_widget) -> cui_item_id;
    pub fn cui_breadcrumbs_activated(breadcrumbs: *const cui_widget) -> cui_item_id;
    pub fn cui_breadcrumbs_activate(breadcrumbs: *mut cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_pattern_name(kind: cui_pattern) -> *const c_char;
    pub fn cui_pattern_create(parent: *mut cui_widget, kind: cui_pattern, title: *const c_char) -> *mut cui_widget;
    pub fn cui_pattern_part(pattern: *mut cui_widget, part: cui_part) -> *mut cui_widget;
    pub fn cui_pattern_event(pattern: *const cui_widget) -> cui_event;
    pub fn cui_pattern_set_records(pattern: *mut cui_widget, cells: *const *const c_char, rows: usize) -> c_int;
    pub fn cui_sidebar_set_items(sidebar: *mut cui_widget, items: *const cui_tree_item, details: *const *const c_char, count: usize) -> c_int;
    pub fn cui_stream_append(stream: *mut cui_widget, chunk: *const c_char) -> c_int;
    pub fn cui_pattern_set_busy(pattern: *mut cui_widget, busy: c_int);
    pub fn cui_pattern_set_filters(pattern: *mut cui_widget, filters: *const cui_record_filter, count: usize, all: c_int) -> c_int;
    pub fn cui_pattern_set_query(pattern: *mut cui_widget, query: *const c_char) -> c_int;
    pub fn cui_pattern_record_source(pattern: *const cui_widget, displayed_row: usize) -> usize;
    pub fn cui_insights_set_series(insights: *mut cui_widget, series: *const cui_insight_series, count: usize) -> c_int;
    pub fn cui_insights_select(insights: *mut cui_widget, id: cui_item_id, point: usize) -> c_int;
    pub fn cui_insights_selection(insights: *const cui_widget, point: *mut usize, value: *mut c_double) -> cui_item_id;
    pub fn cui_pattern_set_items(pattern: *mut cui_widget, items: *const cui_pattern_item, count: usize) -> c_int;
    pub fn cui_pattern_upsert_item(pattern: *mut cui_widget, item: *const cui_pattern_item) -> c_int;
    pub fn cui_pattern_remove_item(pattern: *mut cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_pattern_item_count(pattern: *const cui_widget) -> usize;
    pub fn cui_pattern_item_at(pattern: *const cui_widget, index: usize, item: *mut cui_pattern_item) -> c_int;
    pub fn cui_pattern_item_event_id(pattern: *const cui_widget) -> cui_item_id;
    pub fn cui_pattern_item_part(pattern: *mut cui_widget, id: cui_item_id, part: cui_part) -> *mut cui_widget;
    pub fn cui_picker(parent: *mut cui_widget, kind: cui_picker_kind, placeholder: *const c_char) -> *mut cui_widget;
    pub fn cui_picker_set_items(picker: *mut cui_widget, items: *const cui_choice, count: usize) -> c_int;
    pub fn cui_picker_set_query(picker: *mut cui_widget, query: *const c_char) -> c_int;
    pub fn cui_picker_get_query(picker: *const cui_widget, buffer: *mut c_char, capacity: usize) -> usize;
    pub fn cui_picker_open(picker: *mut cui_widget, return_focus: *mut cui_widget);
    pub fn cui_picker_close(picker: *mut cui_widget);
    pub fn cui_picker_is_open(picker: *const cui_widget) -> c_int;
    pub fn cui_picker_select(picker: *mut cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_picker_accept(picker: *mut cui_widget) -> c_int;
    pub fn cui_picker_selected(picker: *const cui_widget) -> cui_item_id;
    pub fn cui_picker_match_count(picker: *const cui_widget) -> usize;
    pub fn cui_picker_last_event(picker: *const cui_widget) -> cui_picker_event;
    pub fn cui_picker_get_part(picker: *mut cui_widget, part: cui_picker_part) -> *mut cui_widget;
    pub fn cui_table_set_multiple(table: *mut cui_widget, multiple: c_int);
    pub fn cui_table_select_row(table: *mut cui_widget, row: usize, selected: c_int) -> c_int;
    pub fn cui_table_selected_rows(table: *const cui_widget, rows: *mut usize, capacity: usize) -> usize;
    pub fn cui_table_set_editable(table: *mut cui_widget, column: usize, editable: c_int) -> c_int;
    pub fn cui_table_set_cell(table: *mut cui_widget, row: usize, column: usize, text: *const c_char) -> c_int;
    pub fn cui_table_get_cell(table: *const cui_widget, row: usize, column: usize, buffer: *mut c_char, capacity: usize) -> usize;
    pub fn cui_table_source_row(table: *const cui_widget, row: usize) -> usize;
    pub fn cui_table_sort(table: *mut cui_widget, column: usize, descending: c_int, numeric: c_int) -> c_int;
    pub fn cui_table_last_event(table: *const cui_widget, row: *mut c_int, column: *mut c_int) -> cui_table_event;
    pub fn cui_tokens(parent: *mut cui_widget, placeholder: *const c_char, limit: usize) -> *mut cui_widget;
    pub fn cui_tokens_set_items(tokens: *mut cui_widget, items: *const cui_choice, count: usize) -> c_int;
    pub fn cui_tokens_set_selected(tokens: *mut cui_widget, ids: *const cui_item_id, count: usize) -> c_int;
    pub fn cui_tokens_get_selected(tokens: *const cui_widget, ids: *mut cui_item_id, capacity: usize) -> usize;
    pub fn cui_tokens_add(tokens: *mut cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_tokens_remove(tokens: *mut cui_widget, id: cui_item_id) -> c_int;
    pub fn cui_tokens_clear(tokens: *mut cui_widget) -> c_int;
    pub fn cui_tokens_last_event(tokens: *const cui_widget) -> cui_tokens_event;
    pub fn cui_tokens_changed(tokens: *const cui_widget) -> cui_item_id;
    pub fn cui_tokens_get_part(tokens: *mut cui_widget, part: cui_tokens_part) -> *mut cui_widget;
    pub fn cui_tokens_remove_button(tokens: *mut cui_widget, index: usize) -> *mut cui_widget;
}
