#!/usr/bin/env python3
"""Generate the raw Rust ABI from CUI's deliberately simple public C headers.
Stdlib only. Run with --check to reject stale generated declarations.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'bindings/rust/src/sys.rs'
KEYWORDS = {'type', 'match', 'ref', 'loop', 'move', 'self', 'fn', 'mod', 'use', 'in', 'where', 'box'}


def name(value):
    return value + '_' if value in KEYWORDS else value


def ctype(value):
    parts = value.strip().split('*')
    base = parts[0].replace('const', '').strip()
    native = {'void': 'c_void', 'char': 'c_char', 'unsigned char': 'c_uchar',
              'int': 'c_int', 'unsigned': 'c_uint', 'float': 'c_float',
              'double': 'c_double', 'size_t': 'usize', 'uint64_t': 'u64'}.get(base, base)
    for qualifier in parts[:-1]:
        native = ('*const ' if 'const' in qualifier else '*mut ') + native
    return native


def parameter(text):
    text = text.strip()
    match = re.search(r'([A-Za-z_]\w*)\s*$', text)
    if not match:
        raise ValueError(text)
    return name(match[1]), ctype(text[:match.start()].strip())


def enums(text):
    out = []
    for body, enum in re.findall(r'typedef enum \w+\s*{([^}]+)}\s*(\w+)\s*;', text, re.S):
        out.append(f'pub type {enum} = c_int;')
        number = -1
        for entry in body.split(','):
            if not entry.strip():
                continue
            fields = entry.strip().split('=')
            number = int(fields[1], 0) if len(fields) > 1 else number + 1
            out.append(f'pub const {fields[0].strip()}: {enum} = {number};')
    return out


def fields(declaration):
    entries = declaration.strip().split(',')
    match = re.fullmatch(r'(.+?)\b(\w+)\s*(\[\d+\])?', entries[0].strip())
    if not match:
        raise ValueError(declaration)
    base = match[1]
    ctype_base = re.sub(r'\s*\*.*', '', base).strip()
    out = []
    for i, entry in enumerate(entries):
        m = match if i == 0 else re.fullmatch(r'(\**\s*)(\w+)\s*(\[\d+\])?', entry.strip())
        if not m:
            raise ValueError(entry)
        typ = ctype(base if i == 0 else ctype_base + ' ' + m[1])
        if m[3]:
            typ = f'[{typ}; {m[3][1:-1]}]'
        out.append(f'pub {name(m[2])}: {typ},')
    return out


def structs(text):
    out = []
    for body, struct in re.findall(r'typedef struct \w+\s*{([^}]+)}\s*(\w+)\s*;', text, re.S):
        members = [field for line in body.split(';') if line.strip() for field in fields(line)]
        out.append(f'#[repr(C)] #[derive(Clone,Copy,Debug)] pub struct {struct} {{' + ''.join(members) + '}')
        out.append(f'impl Default for {struct} {{ fn default()->Self {{ unsafe {{ std::mem::zeroed() }} }} }}')
    return out


def functions(text):
    clean = re.sub(r'^\s*#.*$', '', text, flags=re.M)
    clean = re.sub(r'typedef.*?;', '', clean, flags=re.S)
    out = []
    for result, fn, args in re.findall(r'([\w\s*]+?)\b(cui_\w+)\s*\(([^;{}]*)\)\s*;', clean):
        result = result.strip().split('}')[-1].strip()
        params = [] if args.strip() in ('', 'void') else [parameter(v) for v in args.split(',')]
        ret = '' if result == 'void' else ' -> ' + ctype(result)
        out.append(f'    pub fn {fn}(' + ', '.join(n + ': ' + t for n, t in params) + ')' + ret + ';')
    return out


def generate():
    out = ['// Generated by tools/generate_rust_bindings.py; do not edit.',
           '#![allow(non_camel_case_types, non_upper_case_globals)]',
           'use std::ffi::{c_char,c_void,c_int,c_uint,c_float,c_double,c_uchar};']
    declarations = []
    for path in sorted((ROOT / 'include').glob('*.h')):
        text = re.sub(r'/\*.*?\*/|//[^\n]*', '', path.read_text(), flags=re.S)
        out.append('// ' + path.name)
        for opaque in re.findall(r'typedef struct (\w+) \w+;', text):
            out.append(f'#[repr(C)] pub struct {opaque} {{ _private: [u8;0] }}')
        out.extend(enums(text))
        out.extend(structs(text))
        declarations.extend(functions(text))
    out += ['pub type cui_canvas_callback = Option<unsafe extern "C" fn(*mut cui_widget,*const cui_canvas_event,*mut c_void)>;',
            'pub type cui_item_id = u64;',
            'pub type cui_callback = Option<unsafe extern "C" fn(*mut cui_widget,*mut c_void)>;',
            'pub type cui_task = Option<unsafe extern "C" fn(*mut c_void)>;',
            'pub type cui_key_callback = Option<unsafe extern "C" fn(*mut cui_widget,cui_key,c_uint,*mut c_void)->c_int>;',
            'pub type cui_dialog_callback = Option<unsafe extern "C" fn(*mut cui_dialog,cui_dialog_result,*const c_char,*mut c_void)>;',
            'unsafe extern "C" {', *declarations, '}']
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    result = generate()
    if '--check' in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            sys.exit('Rust ABI is stale: run python tools/generate_rust_bindings.py')
    else:
        OUTPUT.write_text(result)
