#!/usr/bin/env python3
"""Generate C model data from the exact shared HTML concept fixture."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'examples/chat/fixture.json').read_text())
q=lambda value:json.dumps(value,ensure_ascii=False)
lines=['/* Generated by tools/generate_chat_fixture.py. Sample data only. */']
people=data['people']
for key,messages in {**data['timelines'],'thread':data['threadReplies']}.items():
    day=''; records=[]
    for i,m in enumerate(messages):
        if 'day' in m:day=m['day'];continue
        ident=f'{key}_{i}';p=people[m['by']]
        text=m.get('txt','')
        runs=[]
        for j,part in enumerate(text.split('@mathias')):
            if j:runs.append('{"@mathias","",CUI_CHAT_MENTION}')
            runs.append('{'+q(part)+',"",CUI_CHAT_BODY}')
        lines.append(f'static cui_chat_span spans_{ident}[]={{'+','.join(runs)+'};')
        props=[f'.id={i+1}',f'.author={q(p["name"])}',f'.time={q(m["t"])}',f'.date={q(day)}',f'.spans=spans_{ident}', f'.span_count={len(runs)}','.selected_option=-1']
        day='';flags=(1 if m['by']=='you' else 0)|(2 if m.get('mention') else 0)|(4 if m.get('cont') else 0)
        props.append(f'.flags={flags}')
        if 'reply' in m:props += [f'.reply_id=4',f'.reply_author={q(people[m["reply"]["by"]]["name"])}',f'.reply_text={q(m["reply"]["txt"])}']
        if 'file' in m:
            f=m['file'];lines.append(f'static cui_chat_detail file_{ident}[]='+'{{.id=1,.text='+q(f['name'])+',.detail='+q(f['size']+' · encrypted')+'}};');props +=[f'.attachments=file_{ident}', '.attachment_count=1']
        if 'reacts' in m:
            vals=','.join('{.text='+q(r[0])+f',.count={r[1]},.flags={64 if r[2] else 0}'+'}' for r in m['reacts'])
            lines.append(f'static cui_chat_detail reactions_{ident}[]={{'+vals+'};');props += [f'.reactions=reactions_{ident}',f'.reaction_count={len(m["reacts"])}']
        if 'poll' in m:
            poll=m['poll'];vals=','.join('{.text='+q(o[0])+f',.count={o[1]}'+'}' for o in poll['opts']);lines.append(f'static cui_chat_detail options_{ident}[]={{'+vals+'};');props +=[f'.poll_question={q(poll["q"])}',f'.options=options_{ident}',f'.option_count={len(poll["opts"])}']
        if 'thread' in m:
            faces=','.join('{.id='+str(j+1)+',.title='+q(people[key]['name'])+'}' for j,key in enumerate(m['thread']['who']))
            lines.append(f'static cui_chat_room faces_{ident}[]={{'+faces+'};')
            props += [f'.thread_participants=faces_{ident}',f'.thread_participant_count={len(m["thread"]["who"])}']
        if 'thread' in m:props +=[f'.thread_count={m["thread"]["n"]}',f'.thread_preview={q(m["thread"]["last"])}']
        records.append('{'+','.join(props)+'}')
    lines.append(f'static cui_chat_message history_{key}[]={{'+',\n'.join(records)+'};')
lines.append('typedef struct sample_room { cui_chat_room room; const char *key,*space,*topic; unsigned members; int pinned; cui_chat_message *messages; size_t count; } sample_room;')
lines.append('static sample_room sample_rooms[]={')
for i,r in enumerate(data['rooms']):
    flags=(16 if r['kind']=='room' else 0)|(8 if r.get('online') else 0)|(2 if r.get('hl') else 0)
    key=r['id'];lines.append('{{.id='+str(i+1)+',.title='+q(('#' if r['kind']=='room' else '')+r['name'])+',.trailing='+q(next((m['t'] for m in reversed(data['timelines'][r['id']]) if 't' in m),''))+',.detail='+q(r['last'])+',.unread='+str(r.get('unread',0))+',.flags='+str(flags)+'},'+','.join([q(key),q(r.get('space') or ''),q(r.get('topic',people.get(key,{}).get('id',''))),str(r.get('members',2)),str(int(r.get('fav',False))),f'history_{key}',f'sizeof(history_{key})/sizeof(*history_{key})'])+'},')
lines.append('};')
lines.append('static cui_chat_room sample_spaces[]={')
for i,s in enumerate(data['spaces']):lines.append('{.id='+str(i+1)+',.title='+q(s['name'])+',.unread='+str(s.get('unread',0))+'},')
lines.append('};')
lines.append('static cui_chat_room sample_people[]={')
for i,p in enumerate(people.values()):
    lines.append('{.id='+str(100+i)+',.title='+q(p['name'])+',.detail='+q(p['id'])+',.trailing='+q(p.get('pl','Member'))+',.flags='+str(8 if p.get('online') else 0)+'},')
lines.append('};')
(ROOT/'examples/chat/fixture.h').write_text('\n'.join(lines)+'\n')
