#!/usr/bin/env python3
"""Compile the reference concepts' UI geometry into reusable CUI symbols."""
from pathlib import Path
import struct
from compile_icons import compile_svg
ROOT=Path(__file__).resolve().parents[1]
icons={
'home':'<path d="M4 11 12 4l8 7v9h-5v-6H9v6H4z"/>',
'phone':'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2"/>',
'video':'<rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/>',
'people':'<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20a6.5 6.5 0 0 1 13 0M16 4.5a3.5 3.5 0 0 1 0 7M21.5 20a6.5 6.5 0 0 0-4-6"/>',
'thread':'<path d="M4 5h16v10H9l-5 4zM8 9h8M8 12h5"/>',
'file':'<path d="M14 3H6v18h12V7zM14 3v4h4"/>',
'download':'<path d="M12 3v12M7 10l5 5 5-5M5 20h14"/>',
'poll':'<path d="M5 20V10M12 20V4M19 20v-7"/>',
'emoji':'<circle cx="12" cy="12" r="9"/><path d="M8.5 14a4 4 0 0 0 7 0M9 9.5v.01M15 9.5v.01"/>',
'arrow_right':'<path d="M5 12h14M13 6l6 6-6 6"/>',
'panel':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M15 4v16"/>',
'lock':'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
}
lines=['/* Generated by tools/generate_chat_icons.py from assets/chat SVG. */']
for name,body in icons.items():
    svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+body+'</svg>'
    (ROOT/'assets/chat'/f'{name}.svg').write_text(svg+'\n')
    data=compile_svg(svg);count=struct.unpack_from('<I',data,16)[0]
    lines.append('static const cui_icon_command chat_icon_'+name+'[]={')
    for i in range(count):
        op,color,current,*v=struct.unpack_from('<III6f',data,20+i*36)
        lines.append('{'+str(op)+',{'+','.join(format(x,'.8g') for x in v)+'},'+str(color)+','+str(current)+'},')
    lines.append('};')
lines.append('static cui_icon_asset *chat_symbol(cui_symbol symbol){switch(symbol){')
for name in icons:lines.append('case CUI_SYMBOL_'+name.upper()+':return cui_icon_vector(24,24,chat_icon_'+name+',sizeof(chat_icon_'+name+')/sizeof(*chat_icon_'+name+'));')
lines.append('default:return NULL;}}')
(ROOT/'src/cui_chat_icons.h').write_text('\n'.join(lines)+'\n')
