#!/usr/bin/env python3
"""Generate dependency-free Rust example data from the shared concept fixture."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'examples/chat/fixture.json').read_text())


def string(value):
    return json.dumps(value, ensure_ascii=False) + '.into()'


def avatar(person, square=False):
    name = person['name']
    return ('Avatar { name: ' + string(name) + ', color: color(' + json.dumps(name)
            + '), online: ' + str(person.get('online', False)).lower()
            + ', square: ' + str(square).lower() + ' }')


def message(record, index, day):
    fields = [f'id: {index + 1}', 'author: ' + avatar(DATA['people'][record['by']]),
              'time: ' + string(record['t']), 'date: ' + string(day),
              'author_color: sender_color(' + json.dumps(DATA['people'][record['by']]['name']) + ')',
              'outgoing: ' + str(record['by'] == 'you').lower(),
              'highlighted: ' + str(record.get('mention', False)).lower()]
    spans = []
    for i, part in enumerate(record.get('txt', '').split('@mathias')):
        if i:
            spans.append('Span { text: "@mathias".into(), style: TextStyle::Mention, link: None }')
        spans.append('Span::plain(' + json.dumps(part, ensure_ascii=False) + ')')
    fields.append('body: RichText(vec![' + ','.join(spans) + '])')
    if 'file' in record:
        f = record['file']
        fields.append('attachments: vec![Attachment { id: 1, name: ' + string(f['name'])
                      + ', detail: ' + string(f['size'] + ' · encrypted') + ' }]')
    if 'reacts' in record:
        fields.append('reactions: vec![' + ','.join('Reaction { key: ' + string(r[0])
                      + f', count: {r[1]}, mine: {str(r[2]).lower()}' + ' }'
                      for r in record['reacts']) + ']')
    if 'reply' in record:
        r = record['reply']
        fields.append('reply: Some(Reply { message: 4, author: '
                      + string(DATA['people'][r['by']]['name']) + ', text: ' + string(r['txt']) + ' })')
    if 'poll' in record:
        p = record['poll']
        fields.append('poll: Some(Poll { question: ' + string(p['q'])
                      + ', options: vec![' + ','.join('PollOption { label: ' + string(o[0])
                      + f', votes: {o[1]}' + ' }' for o in p['opts'])
                      + '], selected: None, closed: false })')
    if 'thread' in record:
        t = record['thread']
        fields.append(f'thread: Some(ThreadSummary {{ count: {t["n"]}, preview: '
                      + string(t['last']) + ', participants: vec!['
                      + ','.join(avatar(DATA['people'][k]) for k in t['who']) + '] })')
    return 'Message { ' + ', '.join(fields) + ', ..Message::default() }'


def generate():
    lines = ['// Generated by tools/generate_chat_rust_fixture.py. Do not edit.',
             'use super::model::{color, sender_color, Room};', 'use cui::{chat::*, sys};']
    for key, records in {**DATA['timelines'], 'thread': DATA['threadReplies']}.items():
        day, messages = '', []
        for i, record in enumerate(records):
            if 'day' in record:
                day = record['day']
            else:
                messages.append(message(record, i, day))
                day = ''
        lines.append(f'pub fn {key}() -> Vec<Message> {{ vec![' + ',\n'.join(messages) + '] }')
    lines.append('pub fn rooms() -> Vec<Room> { vec![')
    for i, r in enumerate(DATA['rooms']):
        title = ('#' if r['kind'] == 'room' else '') + r['name']
        last_time = next(m['t'] for m in reversed(DATA['timelines'][r['id']]) if 't' in m)
        lines.append('Room { key: ' + string(r['id']) + ', space: ' + string(r.get('space') or '')
                     + ', topic: ' + string(r.get('topic', DATA['people'].get(r['id'], {}).get('id', '')))
                     + f', members: {r.get("members", 2)}, pinned: {str(r.get("fav", False)).lower()},'
                     + ' nav: NavItem { id: ' + str(i + 1) + ', title: ' + string(title)
                     + ', detail: ' + string(r['last']) + ', trailing: ' + string(last_time)
                     + ', avatar: ' + avatar(r, r['kind'] == 'room')
                     + f', unread: {r.get("unread", 0)}, mention: {str(r.get("hl", False)).lower()},'
                     + ' ..NavItem::default() }, messages: ' + r['id'] + '(), draft: String::new() },')
    lines.append('] }')
    lines.append('pub fn spaces() -> Vec<NavItem> { vec![')
    for i, s in enumerate(DATA['spaces']):
        lines.append('NavItem { id: ' + str(i + 1) + ', title: ' + string(s['name'])
                     + f', unread: {s.get("unread", 0)}, symbol: '
                     + ('sys::CUI_SYMBOL_NONE' if i else 'sys::CUI_SYMBOL_HOME')
                     + ', avatar: Avatar { color: '
                     + (f'cui::chat_color(0.84, 0.12, {s["hue"]}., 1.)' if i else '0')
                     + ', ..Avatar::default() }, ..NavItem::default() },')
    lines.append('] }')
    lines.append('pub fn people() -> Vec<NavItem> { vec![')
    for i, p in enumerate(DATA['people'].values()):
        lines.append(f'NavItem {{ id: {100+i}, title: ' + string(p['name'])
                     + ', detail: ' + string(p['id']) + ', trailing: '
                     + string(p.get('pl', 'Member')) + ', avatar: ' + avatar(p)
                     + ', ..NavItem::default() },')
    lines.append('] }')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'bindings/rust/examples/daylight/fixture.rs'
    content = generate()
    if args.check:
        if target.read_text() != content:
            raise SystemExit('Rust chat fixture is stale; regenerate it')
    else:
        target.write_text(content)
