#!/usr/bin/env python3
"""Keep the Windows DLL's exports equal to the public C declarations."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    names = set()
    for path in (ROOT / 'include').glob('*.h'):
        source = re.sub(r'/\*.*?\*/|//[^\n]*', '', path.read_text(), flags=re.S)
        names.update(re.findall(r'\b(cui_\w+)\s*\([^;{}]*\)\s*;', source))
    output = '; Generated by tools/generate_windows_exports.py\nLIBRARY cui\nEXPORTS\n'
    output += ''.join(f'    {name}\n' for name in sorted(names))
    path = ROOT / 'windows/cui.def'
    if args.check:
        if not path.exists() or path.read_text() != output:
            raise SystemExit('Windows exports are stale; run tools/generate_windows_exports.py')
    else:
        path.write_text(output)
    print(f'Windows DLL exports: {len(names)} public C functions')


if __name__ == '__main__':
    main()
