/* Generated by tools/generate_chat_fixture.py. Sample data only. */
static cui_chat_span spans_design_1[]={{"Pushed room list density options to staging. Compact mode drops the preview line.","",CUI_CHAT_BODY}};
static cui_chat_span spans_design_2[]={{"Compact looks great on a 13\" screen. Can we keep unread rooms bold though?","",CUI_CHAT_BODY}};
static cui_chat_detail reactions_design_2[]={{.text="💯",.count=3,.flags=0},{.text="👀",.count=1,.flags=0}};
static cui_chat_span spans_design_4[]={{"Morning! Three things for crit today:\n1. Composer states — idle, replying, editing\n2. Call tile picture-in-picture\n3. Verification flow copy","",CUI_CHAT_BODY}};
static cui_chat_room faces_design_4[]={{.id=1,.title="Kai Tanaka"},{.id=2,.title="Noor Haddad"},{.id=3,.title="Ben Okafor"}};
static cui_chat_span spans_design_5[]={{"Mocked the PiP tile, export attached.","",CUI_CHAT_BODY}};
static cui_chat_detail file_design_5[]={{.id=1,.text="call-pip-v3.fig",.detail="4.2 MB · encrypted"}};
static cui_chat_span spans_design_6[]={{"Quick vote before we start:","",CUI_CHAT_BODY}};
static cui_chat_detail options_design_6[]={{.text="Speaker focus",.count=4},{.text="Grid",.count=6},{.text="Spotlight + filmstrip",.count=2}};
static cui_chat_span spans_design_7[]={{"For verification I would lead with the emoji compare — it is the one people actually finish. ","",CUI_CHAT_BODY},{"@mathias","",CUI_CHAT_MENTION},{" can you take a pass?","",CUI_CHAT_BODY}};
static cui_chat_detail reactions_design_7[]={{.text="🙌",.count=2,.flags=64}};
static cui_chat_message history_design[]={{.id=2,.author="Kai Tanaka",.time="17:42",.date="Yesterday",.spans=spans_design_1,.span_count=1,.selected_option=-1,.flags=0},
{.id=3,.author="Noor Haddad",.time="17:44",.date="",.spans=spans_design_2,.span_count=1,.selected_option=-1,.flags=0,.reactions=reactions_design_2,.reaction_count=2},
{.id=5,.author="Ana Ribeiro",.time="09:12",.date="Today",.spans=spans_design_4,.span_count=1,.selected_option=-1,.flags=0,.thread_participants=faces_design_4,.thread_participant_count=3,.thread_count=3,.thread_preview="Ben: will pick up the call tile"},
{.id=6,.author="Ben Okafor",.time="09:20",.date="",.spans=spans_design_5,.span_count=1,.selected_option=-1,.flags=0,.attachments=file_design_5,.attachment_count=1},
{.id=7,.author="Ben Okafor",.time="09:21",.date="",.spans=spans_design_6,.span_count=1,.selected_option=-1,.flags=4,.poll_question="Default call layout?",.options=options_design_6,.option_count=3},
{.id=8,.author="Kai Tanaka",.time="09:34",.date="",.spans=spans_design_7,.span_count=3,.selected_option=-1,.flags=2,.reply_id=4,.reply_author="Ana Ribeiro",.reply_text="3. Verification flow copy",.reactions=reactions_design_7,.reaction_count=1}};
static cui_chat_span spans_eng_1[]={{"matrix-rust-sdk bump merged. Sliding sync is on by default for new logins.","",CUI_CHAT_BODY}};
static cui_chat_span spans_eng_2[]={{"Cold start feels much faster on my test account.","",CUI_CHAT_BODY}};
static cui_chat_detail reactions_eng_2[]={{.text="🚀",.count=4,.flags=0}};
static cui_chat_message history_eng[]={{.id=2,.author="Kai Tanaka",.time="08:01",.date="Today",.spans=spans_eng_1,.span_count=1,.selected_option=-1,.flags=0},
{.id=3,.author="Lia Novak",.time="08:15",.date="",.spans=spans_eng_2,.span_count=1,.selected_option=-1,.flags=0,.reactions=reactions_eng_2,.reaction_count=1}};
static cui_chat_span spans_rand_1[]={{"Who took the good kettle from the 3rd floor","",CUI_CHAT_BODY}};
static cui_chat_span spans_rand_2[]={{"it is on a sabbatical","",CUI_CHAT_BODY}};
static cui_chat_message history_rand[]={{.id=2,.author="Noor Haddad",.time="12:30",.date="Today",.spans=spans_rand_1,.span_count=1,.selected_option=-1,.flags=0},
{.id=3,.author="Ben Okafor",.time="12:31",.date="",.spans=spans_rand_2,.span_count=1,.selected_option=-1,.flags=0}};
static cui_chat_span spans_mhq_1[]={{"Is anyone tracking the extensible events proposal?","",CUI_CHAT_BODY}};
static cui_chat_message history_mhq[]={{.id=2,.author="Lia Novak",.time="10:02",.date="Today",.spans=spans_mhq_1,.span_count=1,.selected_option=-1,.flags=0}};
static cui_chat_span spans_ew_1[]={{"Sliding sync notes are up in the room topic.","",CUI_CHAT_BODY}};
static cui_chat_message history_ew[]={{.id=2,.author="Kai Tanaka",.time="11:00",.date="Today",.spans=spans_ew_1,.span_count=1,.selected_option=-1,.flags=0}};
static cui_chat_span spans_talks_1[]={{"Schedule is final. Slides due the day before.","",CUI_CHAT_BODY}};
static cui_chat_message history_talks[]={{.id=2,.author="Noor Haddad",.time="16:10",.date="Mon",.spans=spans_talks_1,.span_count=1,.selected_option=-1,.flags=0}};
static cui_chat_span spans_ana_1[]={{"Can you look at the call tile? The speaking ring feels too thin at 1×.","",CUI_CHAT_BODY}};
static cui_chat_message history_ana[]={{.id=2,.author="Ana Ribeiro",.time="09:40",.date="Today",.spans=spans_ana_1,.span_count=1,.selected_option=-1,.flags=0}};
static cui_chat_span spans_kai_1[]={{"Merged, thanks!","",CUI_CHAT_BODY}};
static cui_chat_message history_kai[]={{.id=2,.author="Mathias",.time="08:20",.date="Today",.spans=spans_kai_1,.span_count=1,.selected_option=-1,.flags=1}};
static cui_chat_span spans_noor_1[]={{"Shared whiteboard.png from today’s session.","",CUI_CHAT_BODY}};
static cui_chat_detail file_noor_1[]={{.id=1,.text="whiteboard.png",.detail="1.1 MB · encrypted"}};
static cui_chat_message history_noor[]={{.id=2,.author="Noor Haddad",.time="19:02",.date="Yesterday",.spans=spans_noor_1,.span_count=1,.selected_option=-1,.flags=0,.attachments=file_noor_1,.attachment_count=1}};
static cui_chat_span spans_thread_0[]={{"Editing needs a clearer escape hint — show “Esc to cancel” inline.","",CUI_CHAT_BODY}};
static cui_chat_span spans_thread_1[]={{"Agreed. The reply bar should show the original sender too.","",CUI_CHAT_BODY}};
static cui_chat_span spans_thread_2[]={{"Will pick up the call tile.","",CUI_CHAT_BODY}};
static cui_chat_message history_thread[]={{.id=1,.author="Kai Tanaka",.time="09:15",.date="",.spans=spans_thread_0,.span_count=1,.selected_option=-1,.flags=0},
{.id=2,.author="Noor Haddad",.time="09:17",.date="",.spans=spans_thread_1,.span_count=1,.selected_option=-1,.flags=0},
{.id=3,.author="Ben Okafor",.time="09:22",.date="",.spans=spans_thread_2,.span_count=1,.selected_option=-1,.flags=0}};
typedef struct sample_room { cui_chat_room room; const char *key,*space,*topic; unsigned members; int pinned; cui_chat_message *messages; size_t count; } sample_room;
static sample_room sample_rooms[]={
{{.id=1,.title="#design-crit",.trailing="09:34",.detail="Kai: lead with the emoji compare",.unread=4,.flags=18},"design","work","Weekly critique · Fridays 15:00 · bring WIP, not finals",14,1,history_design,sizeof(history_design)/sizeof(*history_design)},
{{.id=2,.title="#engineering",.trailing="08:15",.detail="Lia: cold start feels much faster",.unread=8,.flags=16},"eng","work","Builds, deploys and on-call handoffs",42,0,history_eng,sizeof(history_eng)/sizeof(*history_eng)},
{{.id=3,.title="#random",.trailing="12:31",.detail="Ben: it is on a sabbatical",.unread=0,.flags=16},"rand","work","Off-topic, pets, lunch spots",58,0,history_rand,sizeof(history_rand)/sizeof(*history_rand)},
{{.id=4,.title="#Matrix HQ",.trailing="10:02",.detail="Lia: anyone tracking extensible events?",.unread=3,.flags=16},"mhq","matrix","Chat about Matrix, the open standard",9120,0,history_mhq,sizeof(history_mhq)/sizeof(*history_mhq)},
{{.id=5,.title="#Client dev",.trailing="11:00",.detail="Kai: sliding sync notes are up",.unread=0,.flags=16},"ew","matrix","Building Matrix clients",1840,0,history_ew,sizeof(history_ew)/sizeof(*history_ew)},
{{.id=6,.title="#speakers",.trailing="16:10",.detail="Noor: schedule is final",.unread=0,.flags=16},"talks","fosdem","Devroom logistics",31,0,history_talks,sizeof(history_talks)/sizeof(*history_talks)},
{{.id=7,.title="Ana Ribeiro",.trailing="09:40",.detail="Can you look at the call tile?",.unread=1,.flags=10},"ana","","@ana:lumen.chat",2,1,history_ana,sizeof(history_ana)/sizeof(*history_ana)},
{{.id=8,.title="Kai Tanaka",.trailing="08:20",.detail="Merged, thanks!",.unread=0,.flags=8},"kai","","@kai:lumen.chat",2,0,history_kai,sizeof(history_kai)/sizeof(*history_kai)},
{{.id=9,.title="Noor Haddad",.trailing="19:02",.detail="Shared whiteboard.png",.unread=0,.flags=0},"noor","","@noor:matrix.org",2,0,history_noor,sizeof(history_noor)/sizeof(*history_noor)},
};
static cui_chat_room sample_spaces[]={
{.id=1,.title="Home",.unread=0},
{.id=2,.title="Lumen Labs",.unread=12},
{.id=3,.title="Matrix Community",.unread=3},
{.id=4,.title="FOSDEM Devroom",.unread=0},
{.id=5,.title="Game night",.unread=0},
};
static cui_chat_room sample_people[]={
{.id=100,.title="Ana Ribeiro",.detail="@ana:lumen.chat",.trailing="Admin",.flags=8},
{.id=101,.title="Kai Tanaka",.detail="@kai:lumen.chat",.trailing="Moderator",.flags=8},
{.id=102,.title="Noor Haddad",.detail="@noor:matrix.org",.trailing="Member",.flags=0},
{.id=103,.title="Ben Okafor",.detail="@ben:lumen.chat",.trailing="Member",.flags=8},
{.id=104,.title="Lia Novak",.detail="@lia:fosdem.org",.trailing="Member",.flags=0},
{.id=105,.title="Mathias",.detail="@mathias:lumen.chat",.trailing="Admin",.flags=8},
};
